### ISSUE TITLE
Database support?

### ISSUE THREAD

**Issue by mmuruev** [k42b3/psx#16]
It's mostly question. PHP framework without any trace DB support? Others 'miro' does provide something like providers. So how to handle this here?

**Comment by chriskapp** [comment]
Hi, by default we provide a Doctrine DBAL connection which you can use in your controller through the Inject annotation i.e.:

```
class FooController extends ControllerAbstract
{
    /**
     * @Inject
     * @var \Doctrine\DBAL\Connection
     */
    protected $connection;
}
```

The DB credentials must be defined in the `configuration.php` file. If you want to use another DB library you need to add the library to the DI container. Please check the DI chapter (http://psx.readthedocs.org/en/latest/design/dependency_injection.html) of the manual to see howto add/use a service.

**Comment by mmuruev** [comment]
Sounds good enough. No ORM suppost from Doctrine I suppose.
