### ISSUE TITLE
Issue opening sample app in swagger

### ISSUE THREAD

**Issue by ryan-wong** [k42b3/psx#24]
When I hit 127.0.0.1:8080/tool/swagger I get

{
success: false,
title: "PSX\Http\Exception\NotFoundException",
message: "Invalid resource in /Applications/MAMP/htdocs/test/vendor/psx/framework/src/Controller/Generator/SwaggerController.php on line 69",
trace: "#0 /Applications/MAMP/htdocs/test/vendor/psx/framework/src/Filter/ControllerExecutor.php(52): PSX\Framework\Controller\Generator\SwaggerController->onGet() #1 /Applications/MAMP/htdocs/test/vendor/psx/framework/src/Filter/FilterChain.php(79): PSX\Framework\Filter\ControllerExecutor->handle(Object(PSX\Http\Request), Object(PSX\Http\Response), Object(PSX\Framework\Filter\FilterChain)) #2 /Applications/MAMP/htdocs/test/vendor/psx/framework/src/Loader/Loader.php(158): PSX\Framework\Filter\FilterChain->handle(Object(PSX\Http\Request), Object(PSX\Http\Response)) #3 /Applications/MAMP/htdocs/test/vendor/psx/framework/src/Loader/Loader.php(126): PSX\Framework\Loader\Loader->executeController(Object(PSX\Framework\Controller\Generator\SwaggerController), Object(PSX\Http\Request), Object(PSX\Http\Response)) #4 /Applications/MAMP/htdocs/test/vendor/psx/framework/src/Dispatch/Dispatch.php(121): PSX\Framework\Loader\Loader->load(Object(PSX\Http\Request), Object(PSX\Http\Response), Object(PSX\Framework\Loader\Context)) #5 /Applications/MAMP/htdocs/test/public/index.php(33): PSX\Framework\Dispatch\Dispatch->route(Object(PSX\Http\Request), Object(PSX\Http\Response)) #6 /Applications/MAMP/htdocs/test/public/server.php(35): require_once('/Applications/M...') #7 {main}",
context: "65 66 $this-&gt;setHeader('Content-Type', 'application/json'); 67 $this-&gt;setBody($swagger); 68 } else { <b>69 throw new HttpException\NotFoundException('Invalid resource'); </b>70 } 71 } 72 } "
}

**Comment by chriskapp** [comment]
Hi, I have checked the error and there is a wrong route in the sample project. The correct url is i.e.:
`/tool/swagger/*/population`

So the route `/tool/swagger` does not exist anymore. You can get the swagger document only for a specific route. I will update the sample project as soon as possible.

**Comment by chriskapp** [comment]
I have fixed the route in the sample project and tagged a new release. If you have any further problems please let me know.
