### ISSUE TITLE
Improve oauth2 support

### ISSUE THREAD

**Issue by chriskapp** [k42b3/psx#7]
Oauth2 support is currently available but not fully tested and documented. We need to improve the test cases and code coverage. Also we must provide a chapter in the manual howto enable oauth authentication for an API endpoint.

**Comment by mmuruev** [comment]
So what's the status? I need auth, and how to manage it.

**Comment by chriskapp** [comment]
If you have an access token you can use the [authentication filter](http://psx.readthedocs.org/en/latest/concept/authentication.html). If you need an OAuth2 server to issue an access token you can use the `PSX\Oauth2\Provider\TokenAbstract` class but this is the part which is not documented yet.

**Comment by mmuruev** [comment]
Can I use 'regualar' session like auth to? For app UI for example. Does it provide support for this?

**Comment by chriskapp** [comment]
Sessions are not directly supported for authentication since for API endpoints you mostly want to use OAuth2. But you can easily write your own filter or use the session inside a controller. There is also a `session` service to set/get values from the php session so you dont have to use `$_SESSION` in your controller.
